wandb_version: 1

attribution:
  value:
    MODEL_PATH: /Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/logmodels
    filename: ???
dataset:
  value:
    DATA_PATH: /Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/data
    cell_filename: cell_table_size_normalized_cell_labels_corrected_labels
    gmethod: knn
    gtype: cellcell
    k: 6
    response_filename: processed_response
model:
  value:
    MODEL_PATH: /Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/logmodels
    eval: split
    fcriterion: avgcelltype
    feature_dim: ???
    folds: 8
    gcn:
      batch_size: 90
      device: mps
      hidden_dim: ???
      input_dim: ???
      lr: 0.018501446861823
      nm_epochs: 131
    gcriterion: gcn
    gf_dim: 22
    gtype: ???
    logisitic:
      l1_ratio: 0.5167277176540821
      max_iter: 1615
      solver: lbfgs
      tol: 1.846769270910692e-05
    name: logistic
    normalise_features: 'true'
    randomforest:
      bootstrap: 'false'
      criterion: gini
      max_features: sqrt
      min_samples_leaf: 2
      min_samples_split: 3
      n_estimators: 95
      n_jobs: 23
      oob_score: 'true'
      random_state: ???
      warm_start: 'false'
    seed: 39
    test_ratio: 0.521974355230616
    xgboost:
      learning_rate: 0.07213912704178284
      max_depth: 5
      n_estimators: 172
      objective: binary:logistic
