seed: 42
mlmodel:
  name: 'logistic'
  penalty: null
  l1_ratio: 0.5
  solver: 'lbfgs'
  tol: 0.0000001


testportion: 0.3

dataset:
  DATA_PATH: '/Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/data'
  cell_filename: 'cell_table_size_normalized_cell_labels'
  response_filename: 'processed_response'
  gtype: 'celltype'
  k: 7
  method: 'knn'
  use_graph: True
  fcriterion: 'flatcelltype'
  gcriterion: 'laplacian_spectrum'
  cell_radius: 20
  cell_n_thr: 7
  gf_dim: 32