wandb_version: 1

attribution:
  value:
    MODEL_PATH: /Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/logmodels
    filename: ???
dataset:
  value:
    DATA_PATH: /Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/data
    cell_filename: cell_table_size_normalized_cell_labels_corrected_labels
    gmethod: knn
    gtype: cellcell
    k: 13
    response_filename: processed_response
model:
  value:
    MODEL_PATH: /Users/asifkhan/workspace/SpatialCellAnalysis/ML4SpatialAnalysis/logmodels
    eval: split
    fcriterion: avgcelltype
    feature_dim: ???
    folds: 8
    gcn:
      batch_size: 115
      device: mps
      hidden_dim: ???
      input_dim: ???
      lr: 0.01596820983023281
      nm_epochs: 151
    gcriterion: graphproperties
    gf_dim: 56
    gtype: ???
    logisitic:
      l1_ratio: 0.466044549412854
      max_iter: 1651
      solver: lbfgs
      tol: 1.0803468982542254e-05
    name: xgboost
    normalise_features: 'false'
    randomforest:
      bootstrap: 'false'
      criterion: gini
      max_features: sqrt
      min_samples_leaf: 2
      min_samples_split: 4
      n_estimators: 136
      n_jobs: 12
      oob_score: 'true'
      random_state: ???
      warm_start: 'false'
    seed: 34
    test_ratio: 0.2596810392084322
    xgboost:
      learning_rate: 0.09109275272284512
      max_depth: 5
      n_estimators: 124
      objective: binary:logistic
